export enum BreadcrumbLabels {
  MAIN_PAGE = 'MAIN_PAGE',
  ADD_AD = 'ADD_AD',
  SEARCH_FOR_HELP = 'SEARCH_FOR_HELP',
  MY_ACCOUNT = 'MY_ACCOUNT',
  ACCOMMODATION = 'ACCOMMODATION',
  MATERIAL_HELP = 'MATERIAL_HELP',
  TRANSPORT = 'TRANSPORT',
  ABOUT = 'ABOUT_APP',
  STATEMENT = 'STATEMENT',
  PAGE_NOT_FOUND = 'PAGE_NOT_FOUND',
  AD = 'AD',
}
