export enum BreadcrumbLabels {
  MAIN_PAGE = 'MAIN_PAGE',
  ANNOUNCEMENTS = 'ANNOUNCEMENTS',
  ADD_AD = 'ADD_AD',
  SEARCH_FOR_HELP = 'SEARCH_FOR_HELP',
  MY_ACCOUNT = 'MY_ACCOUNT',
  ACCOMMODATION = 'ACCOMMODATION',
  MATERIAL_HELP = 'MATERIAL_HELP',
  TRANSPORT = 'TRANSPORT',
  ABOUT = 'ABOUT_APP',
  STATEMENT = 'STATEMENT',
  DETAILS = 'AD_DETAILS',
}
