export enum BreadcrumbLabels {
  MAIN_PAGE = 'MAIN_PAGE',
  ADD_AD = 'ADD_AD',
  MY_ACCOUNT = 'MY_ACCOUNT',
  ACCOMMODATION = 'ACCOMMODATION',
  MATERIAL_HELP = 'MATERIAL_HELP',
  TRANSPORT = 'TRANSPORT',
}
