export enum CategoryNameKey {
  ACCOMMODATION = 'ACCOMMODATION',
  MATERIAL_HELP = 'MATERIAL_HELP',
  TRANSPORT = 'TRANSPORT',
  HEALTH = 'HEALTH',
  LEGAL_HELP = 'LEGAL_HELP',
  JOB = 'JOB',
  TRANSLATIONS = 'TRANSLATIONS',
  MISC = 'MISC',
}
