export interface DialogData {
  headerText: string;
}

export enum CANCEL_DIALOG_HEADERS {
  CONFIRM_CANCEL_OFFER_NEW = 'CONFIRM_CANCEL_OFFER_NEW',
  CONFIRM_CANCEL_OFFER_EDIT = 'CONFIRM_CANCEL_OFFER_EDIT',
}

export enum SESSION_EXPIRED_HEADERS {
  CONFIRM_SESSION_EXPIRED = 'CONFIRM_SESSION_EXPIRED',
}
