export enum CategoryRoutingName {
  ACCOMMODATION = 'noclegi',
  MATERIAL_HELP = 'pomoc-materialna',
  TRANSPORT = 'transport',
  HEALTH = 'zdrowie',
  LEGAL_HELP = 'pomoc-prawna',
  WORK = 'praca',
  TRANSLATIONS = 'tlumaczenia',
  MISC = 'misc',
  FIND_HELP = 'znajdz-pomoc',
  VIEW_OFFER_ACCOMMODATION = 'view-offer-accommodation',
  VIEW_OFFER_MATERIALAID = 'view-offer-materialaid',
  VIEW_OFFER_TRANSPORT = 'view-offer-transport',
  VIEW_ACCOMMODATION_ID = 'view-offer-accommodation:/id',
  VIEW_MATERIALAID_ID = 'view-offer-materialaid:/id',
  VIEW_TRANSPORT_ID = 'view-offer-transport:/id',
}
