export enum ALERT_TYPES {
  CONFIRM = 'CONFIRM',
  ERROR = 'ERROR',
  WARNING = 'WARNING',
  OFFER_SUCCESS = 'OFFER_SUCCESS',
  MESSAGE_SENT = 'MESSAGE_SENT',
  OFFER_REMOVED = 'OFFER_REMOVED',
  UPDATE_OFFER_SUCCESS = 'UPDATE_OFFER_SUCCESS',
  COPIED_URL = 'COPIED_URL',
}

export interface SNACKBAR_DATA {
  type: ALERT_TYPES;
  link: string;
}
