/**
 * Documentation for ads portal
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AccommodationOfferSearchCriteria {
  capacity?: number;
  lang?: AccommodationOfferSearchCriteria.LangEnum;
}
export namespace AccommodationOfferSearchCriteria {
  export type LangEnum = 'UA' | 'PL' | 'EN' | 'RU';
  export const LangEnum = {
    Ua: 'UA' as LangEnum,
    Pl: 'PL' as LangEnum,
    En: 'EN' as LangEnum,
    Ru: 'RU' as LangEnum,
  };
}
