/**
 * Documentation for ads portal
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Location } from './location';

export interface JobOffer {
  id: number;
  userFirstName: string;
  title: string;
  description: string;
  phoneNumber?: string;
  phoneCountryCode?: string;
  modifiedDate?: string;
  mode: JobOffer.ModeEnum;
  location?: Location;
  industry: Array<JobOffer.IndustryEnum>;
  workTime: Array<JobOffer.WorkTimeEnum>;
  contractType: Array<JobOffer.ContractTypeEnum>;
  language: Array<JobOffer.LanguageEnum>;
  type: JobOffer.TypeEnum;
}
export namespace JobOffer {
  export type ModeEnum = 'ONSITE' | 'TELEWORK' | 'MIXED';
  export const ModeEnum = {
    Onsite: 'ONSITE' as ModeEnum,
    Telework: 'TELEWORK' as ModeEnum,
    Mixed: 'MIXED' as ModeEnum,
  };
  export type IndustryEnum =
    | 'FINANCES'
    | 'HEALTH_AND_SAFETY'
    | 'ENGINEERING'
    | 'EDUCATION'
    | 'HOTEL'
    | 'INTERNET'
    | 'IT'
    | 'ENTERTAINMENT'
    | 'REAL_ASSETS'
    | 'CUSTOMER_SERVICE'
    | 'DESK_JOB'
    | 'MANUAL_JOB'
    | 'CONSULTING'
    | 'MANUFACTURING'
    | 'MARKETING'
    | 'PUBLIC_SECTOR'
    | 'LOGISTICS'
    | 'TRADE'
    | 'HEALTH_AND_BEAUTY'
    | 'MISC';
  export const IndustryEnum = {
    Finances: 'FINANCES' as IndustryEnum,
    HealthAndSafety: 'HEALTH_AND_SAFETY' as IndustryEnum,
    Engineering: 'ENGINEERING' as IndustryEnum,
    Education: 'EDUCATION' as IndustryEnum,
    Hotel: 'HOTEL' as IndustryEnum,
    Internet: 'INTERNET' as IndustryEnum,
    It: 'IT' as IndustryEnum,
    Entertainment: 'ENTERTAINMENT' as IndustryEnum,
    RealAssets: 'REAL_ASSETS' as IndustryEnum,
    CustomerService: 'CUSTOMER_SERVICE' as IndustryEnum,
    DeskJob: 'DESK_JOB' as IndustryEnum,
    ManualJob: 'MANUAL_JOB' as IndustryEnum,
    Consulting: 'CONSULTING' as IndustryEnum,
    Manufacturing: 'MANUFACTURING' as IndustryEnum,
    Marketing: 'MARKETING' as IndustryEnum,
    PublicSector: 'PUBLIC_SECTOR' as IndustryEnum,
    Logistics: 'LOGISTICS' as IndustryEnum,
    Trade: 'TRADE' as IndustryEnum,
    HealthAndBeauty: 'HEALTH_AND_BEAUTY' as IndustryEnum,
    Misc: 'MISC' as IndustryEnum,
  };
  export type WorkTimeEnum = 'FULL_TIME' | 'PART_TIME' | 'TEMPORARY';
  export const WorkTimeEnum = {
    FullTime: 'FULL_TIME' as WorkTimeEnum,
    PartTime: 'PART_TIME' as WorkTimeEnum,
    Temporary: 'TEMPORARY' as WorkTimeEnum,
  };
  export type ContractTypeEnum = 'EMPLOYMENT' | 'SPECIFIC_TASK' | 'MANDATE' | 'B2B';
  export const ContractTypeEnum = {
    Employment: 'EMPLOYMENT' as ContractTypeEnum,
    SpecificTask: 'SPECIFIC_TASK' as ContractTypeEnum,
    Mandate: 'MANDATE' as ContractTypeEnum,
    B2B: 'B2B' as ContractTypeEnum,
  };
  export type LanguageEnum = 'UA' | 'PL' | 'EN' | 'RU';
  export const LanguageEnum = {
    Ua: 'UA' as LanguageEnum,
    Pl: 'PL' as LanguageEnum,
    En: 'EN' as LanguageEnum,
    Ru: 'RU' as LanguageEnum,
  };
  export type TypeEnum = 'JOB';
  export const TypeEnum = {
    Job: 'JOB' as TypeEnum,
  };
}
