/**
 * Documentation for ads portal
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccommodationOffer } from './accommodationOffer';
import { TransportOffer } from './transportOffer';
import { MaterialAidOffer } from './materialAidOffer';

export interface OffersBaseOffer {
  content?: Array<AccommodationOffer | MaterialAidOffer | TransportOffer>;
  totalElements?: number;
  totalPages?: number;
}
