/**
 * Documentation for ads portal
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobOffer } from './jobOffer';
import { OtherOffer } from './otherOffer';
import { AccommodationOffer } from './accommodationOffer';
import { LawOffer } from './lawOffer';
import { TransportOffer } from './transportOffer';
import { HealthOffer } from './healthOffer';
import { MaterialAidOffer } from './materialAidOffer';
import { TranslationOffer } from './translationOffer';

export interface OffersBaseOffer {
  content?: Array<
    | AccommodationOffer
    | HealthOffer
    | JobOffer
    | LawOffer
    | MaterialAidOffer
    | OtherOffer
    | TranslationOffer
    | TransportOffer
  >;
  totalElements?: number;
  totalPages?: number;
}
