/**
 * Documentation for ads portal
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HealthOfferVM } from './healthOfferVM';
import { AccommodationOfferVM } from './accommodationOfferVM';
import { OtherOfferVM } from './otherOfferVM';
import { MaterialAidOfferVM } from './materialAidOfferVM';
import { JobOfferVM } from './jobOfferVM';
import { LawOfferVM } from './lawOfferVM';
import { TranslationOfferVM } from './translationOfferVM';
import { TransportOfferVM } from './transportOfferVM';

export interface OffersVMBaseOfferVM {
  content?: Array<
    | AccommodationOfferVM
    | HealthOfferVM
    | JobOfferVM
    | LawOfferVM
    | MaterialAidOfferVM
    | OtherOfferVM
    | TranslationOfferVM
    | TransportOfferVM
  >;
  totalElements?: number;
  totalPages?: number;
}
