/**
 * Documentation for ads portal
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobOffer } from './jobOffer';
import { AccommodationOffer } from './accommodationOffer';
import { LawOffer } from './lawOffer';
import { TransportOffer } from './transportOffer';
import { HealthOffer } from './healthOffer';
import { MaterialAidOffer } from './materialAidOffer';
import { TranslationsOffer } from 'src/app/find-help/translations-search/translations-search-form/translations-search-form.component';

export interface OffersBaseOffer {
  content?: Array<
    AccommodationOffer | HealthOffer | JobOffer | LawOffer | MaterialAidOffer | TransportOffer | TranslationsOffer
  >;
  totalElements?: number;
  totalPages?: number;
}
