/**
 * Documentation for ads portal
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Location } from './location';

export interface OtherOffer {
  id: number;
  userFirstName: string;
  title: string;
  description: string;
  phoneNumber?: string;
  phoneCountryCode?: string;
  modifiedDate?: string;
  location?: Location;
  type: OtherOffer.TypeEnum;
}
export namespace OtherOffer {
  export type TypeEnum = 'OTHER';
  export const TypeEnum = {
    Other: 'OTHER' as TypeEnum,
  };
}
