/**
 * Documentation for ads portal
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Location } from './location';

export interface TransportOffer {
  id?: number;
  userFirstName: string;
  title: string;
  description: string;
  phoneNumber: string;
  modifiedDate?: string;
  origin: Location;
  destination: Location;
  capacity: number;
  transportDate: string;
  type?: string;
}
