/**
 * Documentation for ads portal
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageableObject';
import { Sort } from './sort';
import { MaterialAidOffer } from './materialAidOffer';

export interface PageMaterialAidOffer {
  totalPages?: number;
  totalElements?: number;
  size?: number;
  content?: Array<MaterialAidOffer>;
  number?: number;
  sort?: Sort;
  pageable?: PageableObject;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  empty?: boolean;
}
