/**
 * Documentation for ads portal
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TranslationOffer {
  id?: number;
  title: string;
  description: string;
  mode?: TranslationOffer.ModeEnum;
  language?: Array<TranslationOffer.LanguageEnum>;
  region?: string;
  city?: string;
  sworn?: boolean;
}
export namespace TranslationOffer {
  export type ModeEnum = 'REMOTE';
  export const ModeEnum = {
    Remote: 'REMOTE' as ModeEnum,
  };
  export type LanguageEnum = 'UA' | 'PL';
  export const LanguageEnum = {
    Ua: 'UA' as LanguageEnum,
    Pl: 'PL' as LanguageEnum,
  };
}
